# Copyright Barry Rowlingson <b.rowlingson@lancaster.ac.uk> and 
# Peter Diggle (c) 1991-3; http://www.maths.lancs.ac.uk/~rowlings/Splancs/
# R port: copyright 1998-2000 by Roger S. Bivand
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#

splancs <- function()
{
#	cat('Splancs version 2.00     Date 23/11/93\n')
#	cat('\n(c) BSR and PJD 1991      Lancaster University\n')
#	cat('                          Lancaster, U.K.\n')
#	cat('\n This version of Splancs is not public domain and\n')
#	cat('must not be copied or redistributed without prior\n')
#	cat('permission of the authors\n')
	'2.01'
}
